### ISSUE TITLE
Strona "Praca Zdalna">- nie działa link

### ISSUE THREAD

**Issue by pwalen** [pwicherski/TestowanieOprogramowania#32]
Link w linii 21 przekierowuje na stronę błędu 404:

"polecam też repozytorium grupy [Testowanie Oprogramowania](https://github.com/pwicherski/TestowanieOprogramowania/blob/master/Materialy/Inne/PracaZdalna.md)\) można zdobyć wiedzę niezbędną do przejścia pierwszej rozmowy o pracę."

![Screen Shot 2019-05-13 at 20 25 22](https://user-images.githubusercontent.com/41115724/57644905-6ed17400-75bd-11e9-95fd-175e90c52886.png)

**Comment by pwicherski** [comment]
Dziękuję za zgłoszenie! :)

Poprawka wdrożona:
https://github.com/pwicherski/TestowanieOprogramowania/commit/7b40ea358a4f09e8482dcbac7766afc8c3ec536f
