### ISSUE TITLE
Poprawione zdanie 

### ISSUE THREAD

**Issue by Wioletta-Czurynska** [pwicherski/TestowanieOprogramowania#40]
W moim odczuciu to zdanie będzie brzmiało lepiej jeśli wyeliminujesz słowo "nadal". Łączenie go z czasem przeszłym powoduje u mnie dysonans. 

Jest: 
Zazwyczaj powodem jest to, iż mimo tego, że jest to banał, to nadal spotkałem przynajmniej jedną osobę, która o to pytała.

Moja propozycja:
Zazwyczaj powodem jest to, iż mimo tego, że jest to banał, to i tak spotykałem osoby, które o to pytały. 

![Screenshot_20200215-082538_Chrome](https://user-images.githubusercontent.com/50742246/74583938-1ce6d000-4fcd-11ea-8821-0ddfdcfecc78.jpg)

**Comment by pwicherski** [comment]
Dzięki za zgłoszenie, zdanie poprawione na bardziej odzwierciedlające to, co chciałem przekazać :)

**Comment by Wioletta-Czurynska** [comment]
Ja się też cieszę, bo pierwszy raz coś zrobiłam w projektach Open Source 😊

Od niedawna uczę się HTML5, CSS, zaczęłam też robić strony na Wordpress.
Chcę pracować zdalnie jako freelancer.

Postanowiłam, że będę  co najmniej raz w tygodniu pomagała w projektach.

W programowaniu nie wiele mogę pomóc, ale w znajdywaniu błędów  treści już
tak ;)


Pozdrawiam
Wiolka Czuryńska

niedz., 16 lut 2020, 15:59 użytkownik Piotr Wicherski <
notifications@github.com> napisał:

**Comment by pwicherski** [comment]
Cała przyjemność po mojej stronie! :)
