### ISSUE TITLE
Nieaktualne blogi i strona uTest.

### ISSUE THREAD

**Issue by Avannah** [pwicherski/TestowanieOprogramowania#44]
1. Kolejne blogi z listy , które nie był aktualizowane ponad 2 lata (zakładka "Blogi" https://github.com/pwicherski/TestowanieOprogramowania/blob/master/gdzie-szukac-wiedzy/blogi.md):

- https://martamaracje.blogspot.com/ - Marta Zajac
- http://testdetective.com/ - Łukasz Rosłonek (dodatkowo strona zmieniła adres na: https://test-detective.blogspot.com/)

2. Nie istnieje strona https://www.utest.com/courses (zakładka "Kursy online" https://github.com/pwicherski/TestowanieOprogramowania/blob/master/kursy-online.md) - może chodziło o https://www.utest.com/academy .
![utest_courses](https://user-images.githubusercontent.com/42976646/85950921-03349c80-b960-11ea-9d0f-26414099aeeb.png)

**Comment by pwicherski** [comment]
Poprawki wprowadzone, dzięki bardzo za zgłoszenie! :)

Tak, faktycznie uTest zmieniło nazwę swojej sekcji z kursami z Courses na Academy.
